export const STEPS = {
    WELCOME: 'WELCOME',
    MENU: 'MENU',

    EXPERIENCES_LIST: 'EXPERIENCES_LIST',
    EXPERIENCE_DETAIL: 'EXPERIENCE_DETAIL',

    BOOKING_START: 'BOOKING_START',
    BOOKING_DATE: 'BOOKING_DATE',
    BOOKING_PEOPLE: 'BOOKING_PEOPLE',

    HANDOFF: 'HANDOFF',
    END: 'END'
}